version: "3.0"

language: en
pipeline:
      - name: "WhitespaceTokenizer"
      - name: "RegexFeaturizer"
      - name: "EntitySynonymMapper"
      - name: "CountVectorsFeaturizer"
      - name: "CountVectorsFeaturizer"
        analyzer: "char_wb"
        min_ngram: 1
        max_ngram: 4
      - name: "DIETClassifier"
      

policies:
  - name: MemoizationPolicy


rest:
  # You don't need to provide anything here - this channel doesn't require any credentials
  credentials: "credentials.yml"
assistant_id: "20240315-204717-steel-reflection"
